language: bash
services: docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=2.1.0
    - PYTHON37=3.7.0
    - PYTHON36=3.6.6
    - PYTHON35=3.5.6
    - PYTHON34=3.4.9
    - PYTHON27=2.7.15
  matrix:
    - PYTHON_VER="${PYTHON37}" ALPINE_VER=3.8 TAGS="${PYTHON_VER},3.7,3,latest"
    - PYTHON_VER="${PYTHON36}" ALPINE_VER=3.8 TAGS="${PYTHON_VER},3.6"
    - PYTHON_VER="${PYTHON35}" ALPINE_VER=3.8 TAGS="${PYTHON_VER},3.5"
    - PYTHON_VER="${PYTHON34}" ALPINE_VER=3.8 TAGS="${PYTHON_VER},3.4"
    - PYTHON_VER="${PYTHON27}" ALPINE_VER=3.8 TAGS="${PYTHON_VER},2.7,2"
    - PYTHON_VER="${PYTHON37}" ALPINE_VER=3.8 PYTHON_DEBUG=1 TAGS="${PYTHON_VER}-debug,3.7-debug,3-debug"
    - PYTHON_VER="${PYTHON36}" ALPINE_VER=3.8 PYTHON_DEBUG=1 TAGS="${PYTHON_VER}-debug,3.6-debug"
    - PYTHON_VER="${PYTHON35}" ALPINE_VER=3.8 PYTHON_DEBUG=1 TAGS="${PYTHON_VER}-debug,3.5-debug"
    - PYTHON_VER="${PYTHON34}" ALPINE_VER=3.8 PYTHON_DEBUG=1 TAGS="${PYTHON_VER}-debug,3.4-debug"
    - PYTHON_VER="${PYTHON27}" ALPINE_VER=3.8 PYTHON_DEBUG=1 TAGS="${PYTHON_VER}-debug,2.7-debug,2-debug"

script:
  - cd "${PYTHON_VER:0:3}/alpine${ALPINE_VER}"
  - travis_retry make

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
